spring:
  thymeleaf:
    # 关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: sean
    password: 123456
    #数据库连接池(spring boot2 自带的连接池)
    hikari:
      #连接池名字
      pool-name: Sean_Hikari_Poll
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认 60000（10分钟）
      idle-timeout: 60000
      #最大连接数，默认是 10
      maximum-pool-size: 10
      #从连接池返回来的连接自动提交
      auto-commit: true
      #连接最大存活时间。0 表示永久存活，默认 180000（30 分钟）max-lifetime: 180000
      max-lifetime: 180000
      #连接超时时间，默认 30000（30 秒）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: select 1
  #redis的配置
  redis:
    port: 5379
    host: localhost
    database: 3
    password: 123456
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认为8
        max-active: 8
        #最大连接阻塞等待时间，默认是-1
        max-wait: 10000ms
        #最大空闲连接，默认是 8
        max-idle: 200
        #最小空闲连接，默认是 0
        min-idle: 5

# mybatis-plus 的配置
mybatis-plus:
  #配置 mapper.xml 映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置 mybatis 数据返回类型别名
  type-aliases-package: com.sean.seckill.model.dto
  #配置 mybatis 全局配置文件
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
#mybatis sql 打印
logging:
  level:
    com.sean.seckill.mapper: debug